spring:
  application:
    name: proxy
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:default
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.aop: DEBUG