spring:
  application:
    name: producer
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:default
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000